services:
  web:
    build: .
    restart: unless-stopped
    container_name: raimundoherrera-web
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    command: ["gunicorn", "raimundoherrera.wsgi", "--bind", "0.0.0.0:${WEB_PORT:-8000}", "--workers", "${GUNICORN_WORKERS:-4}"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
      - npm

  postgres:
    image: postgres:18
    restart: unless-stopped
    container_name: raimundoherrera-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  npm:
    external: true
    name: npm

volumes:
  postgres_data:
